---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build data-scraping container image
    community.general.docker_image:
      build:
        path: /data_scraping
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/data-scraping:{{ tag.stdout}}
      source: build
  - name: Push data-scraping image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/data-scraping:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/data-scraping:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build data-preprocessing container image
    community.general.docker_image:
      build:
        path: /data_preprocessing
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/data-preprocessing:{{ tag.stdout}}
      source: build
  - name: Push data-preprocessing image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/data-preprocessing:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/data-preprocessing:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build dataset-creator container image
    community.general.docker_image:
      build:
        path: /dataset_creator
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/dataset-creator:{{ tag.stdout}}
      source: build
  - name: Push dataset-creator image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/dataset-creator:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/dataset-creator:{{ tag.stdout}}
      push: yes
      source: local
  - name: Build model-finetuner container image
    community.general.docker_image:
      build:
        path: /model_finetuner
        platform: linux/amd64/v2
      name: gcr.io/{{ gcp_project }}/model-finetuner:{{ tag.stdout}}
      source: build
  - name: Push model-finetuner image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/model-finetuner:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/model-finetuner:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > .docker-tag-ml
  # - name: "Remove all unused containers"
  #   shell: docker system prune -a