version: '3.8'

services:
  data_scraping_service:
    build:
      context: ./src/data_scraping
    ports:
      - "5000:5000"
    networks:
      - test-network

  data_preprocessing_service:
    build:
      context: ./src/data_preprocessing
    ports:
      - "5001:5001"
    networks:
      - test-network

  test_runner:
    build:
      context: .
      dockerfile: test_runner/Dockerfile
    volumes:
      - ./tests/integration_tests:/app/tests/integration_tests
    working_dir: /app
    command: ["pytest",
              "tests/integration_tests/test_data_preprocessing.py"]
    networks:
      - test-network
    depends_on:
      - data_scraping_service
      - data_preprocessing_service


networks:
  test-network:
    driver: bridge
