services:
  vector_db_service:
    build:
      context: ./src/vector_db
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend-network
    volumes:
      - ./src/vector_db:/app/src/vector_db
    working_dir: /app
    environment:
      - GCP_PROJECT="ac215-final-project"
      - GCS_BUCKET_NAME="gain-bucket"
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials
    command: ["pipenv", "run", "python", "src/vector_db/cli.py", "--preprocess"]
  backend_service:
    build:
      context: ./src/api_service
    ports:
      - "9000:9000"
    networks:
      - backend-network
  react-app:
    build:
      context: ./src/frontend_react
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/frontend_react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  backend-network:
    driver: bridge
