version: '3.8'

services:
  data_scraping_service:
    build:
      context: ./src/data_scraping
    ports:
      - "5000:5000"
    networks:
      - test-network
    entrypoint: ["/bin/sh", "-c", "echo 'Overriding docker-entrypoint.sh...'"]

  data_preprocessing_service:
    build:
      context: ./src/data_preprocessing
    ports:
      - "5001:5001"
    networks:
      - test-network
    entrypoint: ["/bin/sh", "-c", "echo 'Overriding docker-entrypoint.sh...'"]

  vector_db_service:
    build:
      context: ./src/vector_db
    ports:
      - "5002:5002"
    networks:
      - test-network
    entrypoint: ["/bin/sh", "-c", "echo 'Overriding docker-entrypoint.sh...'"]

  api_service_base:
    build:
      context: ./src/api_service
    ports:
      - "5003:5003"
    networks:
      - test-network
    entrypoint: ["/bin/sh", "-c", "echo 'Overriding docker-entrypoint.sh...'"]

  model_finetuner:
    build:
      context: ./src/model_finetuner
    ports:
      - "5004:5004"
    networks:
      - test-network
    entrypoint: ["/bin/sh", "-c", "echo 'Overriding docker-entrypoint.sh...'"]

  test_runner:
    build:
      context: .
      dockerfile: test_runner/Dockerfile
    volumes:
      - ./tests/integration_tests:/app/tests/integration_tests
    working_dir: /app
    command: ["pipenv", "run", "pytest",
              "tests/integration_tests/"]
    networks:
      - test-network
    depends_on:
      - data_scraping_service
      - data_preprocessing_service
      - vector_db_service
      - api_service_base
      - model_finetuner


networks:
  test-network:
    driver: bridge
