services:
  vector_db_service:
    build:
      context: ./src/vector_db
    ports:
      - "8000:8000"
    networks:
      - test-network

  api_service_base:
    build:
      context: ./src/api_service
    ports:
      - "9000:9000"
    networks:
      - test-network

  test_runner:
    build:
      context: .
      dockerfile: test_runner/Dockerfile
    volumes:
      - ./tests/integration_tests:/app/tests/integration_tests
    working_dir: /app

    networks:
      - test-network
    depends_on:
      - vector_db_service
      - api_service_base

networks:
  test-network:
    driver: bridge
