services:
  backend_service:
    build:
      context: ./src/api_service
    ports:
      - "9000:9000"
    networks:
      - backend-network
  react-app:
    build:
      context: ./src/frontend_react
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend_react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  backend-network:
    driver: bridge
