services:
  backend_service:
    build:
      context: ./src/api_service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - backend-network
    environment:
      GCP_PROJECT: "ac215-final-project"
      GCS_BUCKET_NAME: "gain-bucket"
      CHROMADB_HOST: "gain-vector-db"
      CHROMADB_PORT: 8000
    secrets:
      - google_application_credentials
  react-app:
    build:
      context: ./src/frontend_react
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend_react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
networks:
  backend-network:
    driver: bridge
secrets:
  google_application_credentials:
    file: ./src/secrets/llm-service-account.json
