networks:
    default:
        name: gain-rag-network
        external: true
services:
    gain-vector-db-cli:
        image: gain-vector-db-cli
        container_name: gain-vector-db-cli
        volumes:
            - ../secrets:/secrets
            - ../vector_db:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
            CHROMADB_HOST: gain-vector-db
            CHROMADB_PORT: 8000
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: gain-vector-db
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
