networks:
    default:
        name: gain-rag-network
        external: true
services:
    gain-rag-cli:
        image: gain-rag-cli
        container_name: gain-rag-cli
        volumes:
            - ../secrets:/secrets
            - ../models:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
            GCP_PROJECT: $GCP_PROJECT
        depends_on:
            - chromadb
    chromadb:
        image: chromadb/chroma:latest
        container_name: gain-rag-chromadb
        ports:
            - 8000:8000
        volumes:
            - ./docker-volumes/chromadb:/chroma/chroma
        environment:
            - IS_PERSISTENT=TRUE
            - ANONYMIZED_TELEMETRY=FALSE
            - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
