name: CI on Merge to Main

on:
  push:
    branches:
      - main # Triggers when code is pushed to the main branch
      - milestone4
      - milestone4-RAG
  pull_request:
    branches:
      - main # Runs on PRs to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Docker image
      - name: Build the Docker image
        run: docker build -t gain-rag-cli -f src/models/Dockerfile src/models

      # Run the container in detached mode
      - name: Start container in detached mode
        run: docker run -d --name test_container gain-rag-cli

      # Run test script
      - name: Run test script in container
        run: docker exec test_container python /app/tests/test_script.py

      # Stop and remove the container
      - name: Stop and remove the container
        run: docker rm -f test_container

      # Step 2: Set up Python environment (specifically Python 3.11)
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 2.1: Set PYTHONPATH to include the root directory (or src)
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # Step 3: Install pytest and pytest-cov for coverage
      - name: Install pytest and pytest-cov
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov langchain-core langchain-community
          pip install numpy pre-commit
          pre-commit install-hooks

      # Run pre-commit hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      # Step 4: Run pytest with coverage and generate HTML report
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=html

      # Step 5: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov # The folder where pytest-cov stores HTML reports
